services:

  mysql:
    image: mysql:8.4
    container_name: shortlink-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: Tum@2529
      MYSQL_DATABASE: shortlink

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -uroot -pTum@2529 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  redis:
    image: redis:latest
    container_name: shortlink-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  app:
    image: tumansh03/shortlink-analytics-platform:latest
    container_name: shortlink-app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

    ports:
      - "8081:8081"

    environment:
      SERVER_PORT: 8081

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shortlink
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Tum@2529

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      JWT_SECRET: ThisIsMyVerySecretKeyForShortLinkAnalyticsPlatform2026
      JWT_EXPIRATION: 86400000

volumes:
  mysql-data:
  redis-data: